language: java

jdk:
 - oraclejdk11
addons:
  sonarcloud:
    organization: unige-pinfo-2019

script:
 - mvn clean install
 - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2019_PInfo1 -Dsonar.organization=unige-pinfo-2019 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=22c43efd39e6139462c936f0097b5168f5f0641c
