language: java

jdk:
 - oraclejdk11

script:
 - mvn clean install
 - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2019_PInfo1 -Dsonar.organization=unige-pinfo-2019 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=f6d98cd9feea2500ee6f6526aa25419d80714622
